name: Common Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['25.2.3', '24.3.4']
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp_version}}
        rebar3-version: '3.19.0'
        version-type: 'strict'
    - name: Compile
      run: rebar3 compile
    - name: Unit Tests
      run: rebar3 eunit
    - name: Tests
      run: rebar3 ct --cover
    - name: Dialyzer
      run: rebar3 as check dialyzer
    - name: Xref
      run: rebar3 as check xref
    # - name: Covertool
    #   run: rebar3 covertool generate

    # - uses: codecov/codecov-action@v1
    #   with:
    #     file: _build/test/covertool/chatterbox.covertool.xml
